[advisories]
unsound = "deny"
yanked = "deny"
unmaintained = "deny"

[licenses]
allow-osi-fsf-free = "either"
copyleft = "warn"
allow = ["MPL-2.0"]
exceptions = [{ allow = ["ISC", "MIT", "OpenSSL"], name = "ring" }]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
