on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 18 * * *'

name: Nix
permissions:
  contents: read

jobs:
  flake:
    name: Nix Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Caching
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Flake & Outputs
        run: nix flake check --all-systems

      - name: Build default package
        run: nix build .#

      - name: Build debug package
        run: nix build .#rustls-platform-verifier-dbg
